name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: write
  contents: write

jobs:
  build:
    name: Build Projects
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Network for Upload Artifact
        run: |
          curl -I https://github.com/actions/upload-artifact/releases/download/v3.1.3/upload-artifact-v3.1.3.zip

      - name: Install Mono (for C# build)
        run: |
          sudo apt-get update
          sudo apt-get install -y mono-complete
          mono --version

      - name: Install Kotlin compiler
        run: |
          curl -s https://get.sdkman.io | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin
          kotlin -version
        shell: bash

      - name: Build C++ Project
        run: |
          mkdir -p build/cpp-project
          g++ cpp-project/*.cpp -o build/cpp-project/cpp-program

      - name: Build C# Project
        run: |
          mkdir -p build/csharp-project
          mcs csharp-project/*.cs -out:build/csharp-project/csharp-program.exe

      - name: Build Kotlin Project
        run: |
          mkdir -p build/kotlin-project
          kotlinc kotlin-project/*.kt -include-runtime -d build/kotlin-project/kotlin-program.jar

      - name: Archive Build Artifacts
        run: |
          tar -czf build-artifacts.tar.gz -C build .

      - name: Debug Archive Creation
        run: ls -l build-artifacts.tar.gz

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.2  # 또는 @v4 또는 커밋 해시
        with:
          name: build-artifacts
          path: build-artifacts.tar.gz
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: .

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build-artifacts.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{ github.run_id }}-${{ github.run_number }}"
          name: Release ${{ github.sha }}
          allowUpdates:physics: true
          body: |
            This release contains the compiled binaries for the following projects:
            - C++ Project
            - C# Project
            - Kotlin Project
